sudo: false
language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.7
    - g++-5
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libudev-dev

cache:
  directories:
  - $HOME/SFML_LINUX
  - $HOME/SFML_OSX

script:
  - >
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      chmod +x tests/travis_linux.sh
      tests/travis_linux.sh
    elif [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      chmod +x tests/travis_osx.sh
      tests/travis_osx.sh
    else
      echo 'Invalid OS'
      exit 1
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -x gcov-5 -a "-s /home/travis/build/texus/TGUI -pr"
