sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.7
    - g++-5
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libudev-dev

cache:
  directories:
  - $HOME/SFML

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - >
    if [ ! -d "$HOME/SFML/lib" ]; then
      wget -O SFML.tar.gz https://github.com/LaurentGomila/SFML/archive/2.2.tar.gz;
      tar -xzf SFML.tar.gz;
      cd SFML-2.2;
      cmake -DCMAKE_INSTALL_PREFIX=$HOME/SFML .;
      make -j2 && make install;
      cd ..;
    else
      echo 'Using cached SFML directory.';
    fi

before_script:
  - mkdir build_gcc-4.7
  - mkdir build_gcc-5.1
  - export SFML_ROOT=$HOME/SFML

script:
  - cd build_gcc-5.1
  - export CXX="g++-5"
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTGUI_BUILD_EXAMPLES=TRUE -DTGUI_BUILD_TESTS=TRUE .. && make -j2 && cd tests/ && ./tests && cd ..
  - cd ../build_gcc-4.7
  - export CXX="g++-4.7"
  - cmake .. && make -j2
