language: cpp
compiler: clang

install:
  - sudo apt-get install -y libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libjpeg62
  - git clone https://github.com/LaurentGomila/SFML
  - cd SFML
  - cmake .
  - sudo make install

script: cmake . && make
