language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libudev-dev

install:
  - wget -O SFML.tar.gz https://github.com/LaurentGomila/SFML/archive/2.2.tar.gz
  - tar -xzf SFML.tar.gz
  - cd SFML-2.2
  - cmake .
  - make && sudo make install
  - cd ..

before_script:
  - mkdir build_gcc-4.7
  - mkdir build_gcc-5.1
  - mkdir build_clang-3.4

script:
  - gcc -v
  - gcc-5 -v
  - gcc-5.1 -v
  - clang -v
  - cd build_gcc-4.7
  - cmake -DTGUI_BUILD_EXAMPLES=TRUE -DTGUI_BUILD_TESTS=TRUE .. && make && ./tests/tests
  - export CXX="g++-5"
  - cd ../build_gcc-5.1
  - cmake .. && make
  - export CXX="clang++"
  - cd ../build_clang-3.4
  - cmake .. && make
  - cd ..
