sudo: false
language: cpp

git:
  depth: 1

os: linux
cache:
  directories:
    - $HOME/SFML_LINUX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.7
    - g++-5

    - libfreetype6-dev
    - libjpeg-dev
    - libx11-dev
    - libxrandr-dev
    - libxcb1-dev
    - libx11-xcb-dev
    - libxcb-randr0-dev
    - libxcb-image0-dev
    - libgl1-mesa-dev
    - libflac-dev
    - libogg-dev
    - libvorbis-dev
    - libvorbisenc2
    - libvorbisfile3
    - libopenal-dev
    - libpthread-stubs0-dev

    - libglew-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libudev-dev

script:
  - chmod +x tests/travis_linux_tests.sh
  - tests/travis_linux_tests.sh

after_success:
  - >
    if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == g++-5 ]]; then
      bash <(curl -s https://codecov.io/bash) -x gcov-5 -a "-s /home/travis/build/texus/TGUI -pr"
    fi
